-- DROP TRIGGER CHECK_INSERT_ARTISTE_TITRE ON ARTISTE_TITRE;
-- DROP TRIGGER CHECK_INSERT_ARTISTE_ALBUM ON ARTISTE_ALBUM;
-- DROP FUNCTION artisteExists(VARCHAR(15));
-- DROP FUNCTION insertNewArtist();
DROP FUNCTION raiseNotice(text);
