DROP TABLE UTILISATEUR CASCADE;
DROP TABLE ALBUM CASCADE;
DROP TABLE ARTISTE CASCADE;
DROP TABLE ALBUM_TITRE;
DROP TABLE ARTISTE_ALBUM;
DROP TABLE ARTISTE_TITRE;
DROP TABLE ECOUTE;
DROP TABLE LISTE_ALBUM;
DROP TABLE LISTE_ARTISTE;
DROP TABLE LISTE_TITRE;
DROP TABLE PLAYLIST CASCADE;
DROP TABLE PLAYLIST_TITRE;
DROP TABLE TITRE;

DROP TYPE GENRE_MUSIQUE;
