DROP TABLE ECOUTE;
DROP TABLE LISTE_ALBUM;
DROP TABLE LISTE_ARTISTE;
DROP TABLE LISTE_TITRE;
DROP TABLE PLAYLIST_TITRE;
DROP TABLE PLAYLIST;
DROP TABLE TITRE;
DROP TABLE ALBUM;
DROP TABLE ARTISTE;
DROP TABLE UTILISATEUR;


DROP TYPE GENRE_MUSIQUE;
DROP SEQUENCE TITRE_SEQ;
DROP SEQUENCE PLAYLIST_SEQ;
