SELECT raiseNotice('TEST INSERTION TABLES');

SELECT raiseNotice('INSERTION DANS UTILISATEUR:');
INSERT INTO UTILISATEUR VALUES ('1', 'helloworld', 'alexis', 'Durieux', 'Alexis', 22);
SELECT * FROM UTILISATEUR;

SELECT raiseNotice('INSERTION DANS TITRE:');
INSERT INTO TITRE VALUES ('1', 'Get Lucky', 180);
SELECT * FROM TITRE;

SELECT raiseNotice('INSERTION DANS ALBUM:');
INSERT INTO ALBUM VALUES ('Random Access Memory', 'electronique', 2013);
SELECT * FROM ALBUM;

SELECT raiseNotice('INSERTION DANS ALBUM_TITRE:');
INSERT INTO ALBUM_TITRE VALUES ('1', 'Random Access Memory');
SELECT * FROM ALBUM_TITRE;

SELECT raiseNotice('INSERTION DANS ARTISTE:');
INSERT INTO ARTISTE VALUES ('Daft Punk', 'français');
SELECT * FROM ARTISTE;

SELECT raiseNotice('INSERTION DANS ARTISTE_TITRE:');
INSERT INTO ARTISTE_TITRE VALUES ('1', 'Daft Punk');
SELECT * FROM ARTISTE_TITRE;

SELECT raiseNotice('INSERTION DANS ARTISTE_ALBUM:');
INSERT INTO ARTISTE_ALBUM VALUES ('Daft Punk', 'Random Access Memory');
SELECT * FROM ARTISTE_ALBUM;

SELECT raiseNotice('INSERTION DANS LISTE_TITRE:');
INSERT INTO LISTE_TITRE VALUES ('1', '1');
SELECT * FROM LISTE_TITRE;

SELECT raiseNotice('INSERTION DANS LISTE_ALBUM:');
INSERT INTO LISTE_ALBUM VALUES ('1', 'Random Access Memory');
SELECT * FROM LISTE_ALBUM;

SELECT raiseNotice('INSERTION DANS LISTE_ARTISTE:');
INSERT INTO LISTE_ARTISTE VALUES ('1', 'Daft Punk');
SELECT * FROM LISTE_ARTISTE;

SELECT raiseNotice('INSERTION DANS ECOUTE:');
INSERT INTO ECOUTE VALUES ('1', DEFAULT,'1');
SELECT * FROM ECOUTE;

SELECT raiseNotice('INSERTION DANS PLAYLIST:');
INSERT INTO PLAYLIST VALUES ('1', 'Playlist éléctronique', '1');
SELECT * FROM PLAYLIST;

SELECT raiseNotice('INSERTION PLAYLIST_TITRE:');
INSERT INTO PLAYLIST_TITRE VALUES ('1', '1');
SELECT * FROM PLAYLIST;


SELECT raiseNotice('TEST TRIGGER ARTISTE_TITRE');
DELETE FROM ARTISTE_ALBUM WHERE nomArtiste = 'Daft Punk';
INSERT INTO ARTISTE_TITRE VALUES ('1', 'Daft Punk');
SELECT * FROM ARTISTE;

SELECT raiseNotice('TEST TRIGGER ARTISTE_ALBUM');
DELETE FROM ARTISTE_ALBUM WHERE nomArtiste = 'Daft Punk';
INSERT INTO ARTISTE_ALBUM VALUES ('Daft Punk', 'Random Access Memory');
SELECT * FROM ARTISTE;

SELECT raiseNotice('Cleaning Tables...');

DELETE FROM PLAYLIST_TITRE WHERE titreId = '1';
DELETE FROM PLAYLIST WHERE id = '1';
DELETE FROM ECOUTE WHERE userId = '1';
DELETE FROM LISTE_ARTISTE WHERE userId = '1';
DELETE FROM LISTE_ALBUM WHERE userId = '1';
DELETE FROM LISTE_TITRE WHERE userId = '1';
DELETE FROM ARTISTE_ALBUM WHERE nomArtiste = 'Daft Punk';
DELETE FROM ARTISTE_TITRE WHERE titreId = '1';
DELETE FROM ARTISTE WHERE nom = 'Daft Punk';
DELETE FROM ALBUM_TITRE WHERE titreId = '1';
DELETE FROM ALBUM WHERE nom = 'Random Access Memory';
DELETE FROM TITRE WHERE id = '1';
DELETE FROM UTILISATEUR WHERE id = '1'
